### ISSUE TITLE
mktemp: too few X's on line 232

### ISSUE THREAD

**Issue by sweetbbak** [llimllib/ytgif#14]
using latest version of yt-dlp and gifsicle. the script has trouble making a tmp directory and returns the error "mktemp: Too few X's" I tried it with a few of the test commands and a few of my own.

**Comment by llimllib** [comment]
Interesting! Can you run it with `-v` and post the full command and the output you get?

**Comment by llimllib** [comment]
I realized I don't actually need that cd to temp any longer anyway, so I removed it in https://github.com/llimllib/ytgif/commit/b6b322775bdfd33f1bdc7d12082216447fb10cce

(The script uses all absolute paths to its cache dir)

**Comment by sweetbbak** [comment]
Awesome, thanks for that. I can still run it with -v if you would like.
